<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $table = 'orders';
    protected $fillable = [
        'image1',
        'image2',
        'image3',
        'image4',
        'deposit',
        'balance',
        'issued_date',
        'issued_paid',
        'issued_payment_via',
        'product1',
        'product2',
        'product3',
        'product4',
        'product2',
        'product3',
        'product4',
        'product5',
        'product6',
        'product7',
        'product8',
        'product9',
        'product10',
        'product11',
        'product12',
        'product13',
        'product14',
        'product15',
        'qtyproduct1',
        'qtyproduct2',
        'qtyproduct3',
        'qtyproduct4',
        'qtyproduct5',
        'qtyproduct6',
        'qtyproduct7',
        'qtyproduct8',
        'qtyproduct9',
        'qtyproduct10',
        'qtyproduct11',
        'qtyproduct12',
        'qtyproduct13',
        'qtyproduct14',
        'qtyproduct15',
        'price_product1',
        'price_product2',
        'price_product3',
        'price_product4',
        'price_product5',
        'price_product6',
        'price_product7',
        'price_product8',
        'price_product9',
        'price_product10',
        'price_product11',
        'price_product12',
        'price_product13',
        'price_product14',
        'price_product15',
        'total_price1',
        'total_price2',
        'total_price3',
        'total_price4',
        'total_price5',
        'total_price6',
        'total_price7',
        'total_price8',
        'total_price9',
        'total_price10',
        'total_price11',
        'total_price12',
        'total_price13',
        'total_price14',
        'total_price15',
        'pd_discount1',
        'pd_discount2',
        'pd_discount3',
        'pd_discount4',
        'pd_discount5',
        'pd_discount6',
        'pd_discount7',
        'pd_discount8',
        'pd_discount9',
        'pd_discount10',
        'pd_discount11',
        'pd_discount12',
        'pd_discount13',
        'pd_discount14',
        'pd_discount15',
        'arrivelocation',
        'deliverytime',
        'discount',
        'order_phone',
        'order_customer',
        'date',
        'totalprice',
        'order_date',
        'shipto',
        'attendto',
        'address',
        'issued_by',
        'term',
        'seller',
        'invoice',
    ];
}
